/*
 * Created on 6 Sep 2016 ( Time 17:16:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service;

import java.util.List;

import com.kumasi.debtmonkey.model.AccountAddress;

/**
 * Business Service Interface for entity AccountAddress.
 */
public interface AccountAddressService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	AccountAddress findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AccountAddress> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AccountAddress save(AccountAddress entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccountAddress update(AccountAddress entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AccountAddress create(AccountAddress entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
