/*
 * Created on 23 Nov 2016 ( Time 15:22:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service;

import java.util.List;

import com.kumasi.debtmonkey.model.PaymentSchedule;

/**
 * Business Service Interface for entity PaymentSchedule.
 */
public interface PaymentScheduleService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PaymentSchedule findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PaymentSchedule> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PaymentSchedule save(PaymentSchedule entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentSchedule update(PaymentSchedule entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentSchedule create(PaymentSchedule entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
