/*
 * Created on 11 Feb 2017 ( Time 18:00:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service;

import java.util.List;

import com.kumasi.debtmonkey.model.PaymentHistory;

/**
 * Business Service Interface for entity PaymentHistory.
 */
public interface PaymentHistoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idpaymentHistory
	 * @return entity
	 */
	PaymentHistory findById( Integer idpaymentHistory  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PaymentHistory> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PaymentHistory save(PaymentHistory entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentHistory update(PaymentHistory entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentHistory create(PaymentHistory entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idpaymentHistory
	 */
	void delete( Integer idpaymentHistory );


}
