/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.business.service;

import java.util.List;

import net.kumasi.debtmonkey.domain.UserRole;

/**
 * Business Service Interface for entity UserRole.
 */
public interface UserRoleService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userAccountId
	 * @param roleRoleId
	 * @return entity
	 */
	UserRole findById( Integer userAccountId, Integer roleRoleId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserRole> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserRole save(UserRole entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserRole update(UserRole entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserRole create(UserRole entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userAccountId
	 * @param roleRoleId
	 */
	void delete( Integer userAccountId, Integer roleRoleId );


}
