/*
 * Created on 6 Sep 2016 ( Time 17:16:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.listitem;

import com.kumasi.debtmonkey.model.AccountType;
import com.kumasi.debtmonkey.web.common.ListItem;

public class AccountTypeListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public AccountTypeListItem(AccountType accountType) {
		super();

		this.value = ""
			 + accountType.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = accountType.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
