/*
 * Created on 6 Sep 2016 ( Time 17:16:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.listitem;

import com.kumasi.debtmonkey.model.Account;
import com.kumasi.debtmonkey.web.common.ListItem;

public class AccountListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public AccountListItem(Account account) {
		super();

		this.value = ""
			 + account.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = account.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
