/*
 * Created on 23 Nov 2016 ( Time 14:35:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.listitem;

import com.kumasi.debtmonkey.model.PaymentHistory;
import com.kumasi.debtmonkey.web.common.ListItem;

public class PaymentHistoryListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PaymentHistoryListItem(PaymentHistory paymentHistory) {
		super();

		this.value = ""
			 + paymentHistory.getIdpaymentHistory()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = paymentHistory.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
