/*
 * Created on 23 Nov 2016 ( Time 15:22:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.listitem;

import com.kumasi.debtmonkey.model.PaymentSchedule;
import com.kumasi.debtmonkey.web.common.ListItem;

public class PaymentScheduleListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PaymentScheduleListItem(PaymentSchedule paymentSchedule) {
		super();

		this.value = ""
			 + paymentSchedule.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = paymentSchedule.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
