/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.debtmonkey.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.debtmonkey.domain.jpa.AccountAddressEntity;
import net.kumasi.debtmonkey.persistence.commons.jpa.GenericJpaService;
import net.kumasi.debtmonkey.persistence.commons.jpa.JpaOperation;
import net.kumasi.debtmonkey.persistence.services.AccountAddressPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "AccountAddress" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AccountAddressPersistenceJPA extends GenericJpaService<AccountAddressEntity, Integer> implements AccountAddressPersistence {

	/**
	 * Constructor
	 */
	public AccountAddressPersistenceJPA() {
		super(AccountAddressEntity.class);
	}

	@Override
	public AccountAddressEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(AccountAddressEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("AccountAddressEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
