/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.debtmonkey.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.debtmonkey.domain.jpa.UserRoleEntity;
import net.kumasi.debtmonkey.domain.jpa.UserRoleEntityKey;
import net.kumasi.debtmonkey.persistence.commons.jpa.GenericJpaService;
import net.kumasi.debtmonkey.persistence.commons.jpa.JpaOperation;
import net.kumasi.debtmonkey.persistence.services.UserRolePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "UserRole" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserRolePersistenceJPA extends GenericJpaService<UserRoleEntity, UserRoleEntityKey> implements UserRolePersistence {

	/**
	 * Constructor
	 */
	public UserRolePersistenceJPA() {
		super(UserRoleEntity.class);
	}

	@Override
	public UserRoleEntity load( Integer userAccountId, Integer roleRoleId ) {
		// Build the composite key
		UserRoleEntityKey key = new UserRoleEntityKey( userAccountId, roleRoleId );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer userAccountId, Integer roleRoleId ) {
		// Build the composite key
		UserRoleEntityKey key = new UserRoleEntityKey( userAccountId, roleRoleId );
		return super.delete( key );
	}

	@Override
	public boolean delete(UserRoleEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			UserRoleEntityKey key = new UserRoleEntityKey( entity.getUserAccountId(), entity.getRoleRoleId() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UserRoleEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
