/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.debtmonkey.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.debtmonkey.domain.jpa.UserAccountEntity;
import net.kumasi.debtmonkey.persistence.commons.jpa.GenericJpaService;
import net.kumasi.debtmonkey.persistence.commons.jpa.JpaOperation;
import net.kumasi.debtmonkey.persistence.services.UserAccountPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "UserAccount" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserAccountPersistenceJPA extends GenericJpaService<UserAccountEntity, Integer> implements UserAccountPersistence {

	/**
	 * Constructor
	 */
	public UserAccountPersistenceJPA() {
		super(UserAccountEntity.class);
	}

	@Override
	public UserAccountEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(UserAccountEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UserAccountEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
