/*
 * Created on 17 Feb 2017 ( Time 16:36:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkey.domain.Role;
import net.kumasi.debtmonkey.domain.jpa.RoleEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class RoleServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public RoleServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'RoleEntity' to 'Role'
	 * @param roleEntity
	 */
	public Role mapRoleEntityToRole(RoleEntity roleEntity) {
		if(roleEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Role role = map(roleEntity, Role.class);

		return role;
	}
	
	/**
	 * Mapping from 'Role' to 'RoleEntity'
	 * @param role
	 * @param roleEntity
	 */
	public void mapRoleToRoleEntity(Role role, RoleEntity roleEntity) {
		if(role == null) {
			return;
		}

		//--- Generic mapping 
		map(role, roleEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}