/*
 * Created on 24 Nov 2016 ( Time 14:57:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
