/*
 * Created on 11 Feb 2017 ( Time 18:00:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
