/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.debtmonkey.web.common.AbstractController;
import net.kumasi.debtmonkey.web.common.FormMode;
import net.kumasi.debtmonkey.web.common.Message;
import net.kumasi.debtmonkey.web.common.MessageType;

//--- Entities
import net.kumasi.debtmonkey.domain.Role;
import net.kumasi.debtmonkey.domain.UserAccount;

//--- Services 
import net.kumasi.debtmonkey.business.service.RoleService;
import net.kumasi.debtmonkey.business.service.UserAccountService;

//--- List Items 
import net.kumasi.debtmonkey.web.listitem.UserAccountListItem;

/**
 * Spring MVC controller for 'Role' management.
 */
@Controller
@RequestMapping("/role")
public class RoleController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "role";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "role/form";
	private static final String JSP_LIST   = "role/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/role/create";
	private static final String SAVE_ACTION_UPDATE   = "/role/update";

	//--- Main entity service
	@Resource
    private RoleService roleService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private UserAccountService userAccountService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public RoleController() {
		super(RoleController.class, MAIN_ENTITY_NAME );
		log("RoleController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "UserAccount"
	 * @param model
	 */
	private void populateListOfUserAccountItems(Model model) {
		List<UserAccount> list = userAccountService.findAll();
		List<UserAccountListItem> items = new LinkedList<UserAccountListItem>();
		for ( UserAccount userAccount : list ) {
			items.add(new UserAccountListItem( userAccount ) );
		}
		model.addAttribute("listOfUserAccountItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param role
	 */
	private void populateModel(Model model, Role role, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, role);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfUserAccountItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Role found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Role> list = roleService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Role
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Role role = new Role();	
		populateModel( model, role, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Role
	 * @param model Spring MVC model
	 * @param roleId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{roleId}")
	public String formForUpdate(Model model, @PathVariable("roleId") Integer roleId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Role role = roleService.findById(roleId);
		populateModel( model, role, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param role  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Role role, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Role roleCreated = roleService.create(role); 
				model.addAttribute(MAIN_ENTITY_NAME, roleCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, role.getRoleId() );
			} else {
				populateModel( model, role, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "role.error.create", e);
			populateModel( model, role, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param role  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Role role, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Role roleSaved = roleService.update(role);
				model.addAttribute(MAIN_ENTITY_NAME, roleSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, role.getRoleId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, role, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "role.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, role, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param roleId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{roleId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("roleId") Integer roleId) {
		log("Action 'delete'" );
		try {
			roleService.delete( roleId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "role.error.delete", e);
		}
		return redirectToList();
	}

}
