/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.debtmonkey.web.common.AbstractController;
import net.kumasi.debtmonkey.web.common.FormMode;
import net.kumasi.debtmonkey.web.common.Message;
import net.kumasi.debtmonkey.web.common.MessageType;

//--- Entities
import net.kumasi.debtmonkey.domain.UserRole;

//--- Services 
import net.kumasi.debtmonkey.business.service.UserRoleService;


/**
 * Spring MVC controller for 'UserRole' management.
 */
@Controller
@RequestMapping("/userRole")
public class UserRoleController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "userRole";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "userRole/form";
	private static final String JSP_LIST   = "userRole/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/userRole/create";
	private static final String SAVE_ACTION_UPDATE   = "/userRole/update";

	//--- Main entity service
	@Resource
    private UserRoleService userRoleService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public UserRoleController() {
		super(UserRoleController.class, MAIN_ENTITY_NAME );
		log("UserRoleController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param userRole
	 */
	private void populateModel(Model model, UserRole userRole, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, userRole);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of UserRole found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<UserRole> list = userRoleService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new UserRole
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		UserRole userRole = new UserRole();	
		populateModel( model, userRole, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing UserRole
	 * @param model Spring MVC model
	 * @param userAccountId  primary key element
	 * @param roleRoleId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{userAccountId}/{roleRoleId}")
	public String formForUpdate(Model model, @PathVariable("userAccountId") Integer userAccountId, @PathVariable("roleRoleId") Integer roleRoleId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		UserRole userRole = userRoleService.findById(userAccountId, roleRoleId);
		populateModel( model, userRole, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param userRole  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid UserRole userRole, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				UserRole userRoleCreated = userRoleService.create(userRole); 
				model.addAttribute(MAIN_ENTITY_NAME, userRoleCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, userRole.getUserAccountId(), userRole.getRoleRoleId() );
			} else {
				populateModel( model, userRole, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "userRole.error.create", e);
			populateModel( model, userRole, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param userRole  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid UserRole userRole, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				UserRole userRoleSaved = userRoleService.update(userRole);
				model.addAttribute(MAIN_ENTITY_NAME, userRoleSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, userRole.getUserAccountId(), userRole.getRoleRoleId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, userRole, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "userRole.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, userRole, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param userAccountId  primary key element
	 * @param roleRoleId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{userAccountId}/{roleRoleId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("userAccountId") Integer userAccountId, @PathVariable("roleRoleId") Integer roleRoleId) {
		log("Action 'delete'" );
		try {
			userRoleService.delete( userAccountId, roleRoleId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "userRole.error.delete", e);
		}
		return redirectToList();
	}

}
