/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.persistence.services.fake;

import java.util.List;
import java.util.Map;

import net.kumasi.debtmonkey.domain.jpa.RoleEntity;
import net.kumasi.debtmonkey.persistence.commons.fake.GenericFakeService;
import net.kumasi.debtmonkey.persistence.services.RolePersistence;

/**
 * Fake persistence service implementation ( entity "Role" )
 *
 * @author Telosys Tools Generator
 */
public class RolePersistenceFAKE extends GenericFakeService<RoleEntity> implements RolePersistence {

	public RolePersistenceFAKE () {
		super(RoleEntity.class);
	}
	
	protected RoleEntity buildEntity(int index) {
		RoleEntity entity = new RoleEntity();
		// Init fields with mock values
		entity.setRoleId( nextInteger() ) ;
		entity.setRoleName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(RoleEntity entity) {
		log("delete ( RoleEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer roleId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RoleEntity entity) {
		log("insert ( RoleEntity : " + entity + ")" ) ;
	}

	public RoleEntity load( Integer roleId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RoleEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RoleEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RoleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RoleEntity save(RoleEntity entity) {
		log("insert ( RoleEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RoleEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
