/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.persistence.services.fake;

import java.util.List;
import java.util.Map;

import net.kumasi.debtmonkey.domain.jpa.UserAccountEntity;
import net.kumasi.debtmonkey.persistence.commons.fake.GenericFakeService;
import net.kumasi.debtmonkey.persistence.services.UserAccountPersistence;

/**
 * Fake persistence service implementation ( entity "UserAccount" )
 *
 * @author Telosys Tools Generator
 */
public class UserAccountPersistenceFAKE extends GenericFakeService<UserAccountEntity> implements UserAccountPersistence {

	public UserAccountPersistenceFAKE () {
		super(UserAccountEntity.class);
	}
	
	protected UserAccountEntity buildEntity(int index) {
		UserAccountEntity entity = new UserAccountEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setUserName( nextString() ) ;
		entity.setEmailAddress( nextString() ) ;
		entity.setPassword( nextString() ) ;
		entity.setFirstName( nextString() ) ;
		entity.setLastName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(UserAccountEntity entity) {
		log("delete ( UserAccountEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(UserAccountEntity entity) {
		log("insert ( UserAccountEntity : " + entity + ")" ) ;
	}

	public UserAccountEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<UserAccountEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<UserAccountEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<UserAccountEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public UserAccountEntity save(UserAccountEntity entity) {
		log("insert ( UserAccountEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<UserAccountEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
