/*
 * Created on 11 Feb 2017 ( Time 18:00:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.debtmonkey.model.Account;
import com.kumasi.debtmonkey.model.jpa.AccountEntity;
import com.kumasi.debtmonkey.model.jpa.UserAccountEntity;
import com.kumasi.debtmonkey.model.jpa.AccountTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccountServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccountServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AccountEntity' to 'Account'
	 * @param accountEntity
	 */
	public Account mapAccountEntityToAccount(AccountEntity accountEntity) {
		if(accountEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Account account = map(accountEntity, Account.class);

		//--- Link mapping ( link to UserAccount )
		if(accountEntity.getUserAccount() != null) {
			account.setUserAccountId(accountEntity.getUserAccount().getId());
		}
		//--- Link mapping ( link to AccountType )
		if(accountEntity.getAccountType() != null) {
			account.setAccountTypeId(accountEntity.getAccountType().getId());
		}
		return account;
	}
	
	/**
	 * Mapping from 'Account' to 'AccountEntity'
	 * @param account
	 * @param accountEntity
	 */
	public void mapAccountToAccountEntity(Account account, AccountEntity accountEntity) {
		if(account == null) {
			return;
		}

		//--- Generic mapping 
		map(account, accountEntity);

		//--- Link mapping ( link : account )
		if( hasLinkToUserAccount(account) ) {
			UserAccountEntity userAccount1 = new UserAccountEntity();
			userAccount1.setId( account.getUserAccountId() );
			accountEntity.setUserAccount( userAccount1 );
		} else {
			accountEntity.setUserAccount( null );
		}

		//--- Link mapping ( link : account )
		if( hasLinkToAccountType(account) ) {
			AccountTypeEntity accountType2 = new AccountTypeEntity();
			accountType2.setId( account.getAccountTypeId() );
			accountEntity.setAccountType( accountType2 );
		} else {
			accountEntity.setAccountType( null );
		}

	}
	
	/**
	 * Verify that UserAccount id is valid.
	 * @param UserAccount UserAccount
	 * @return boolean
	 */
	private boolean hasLinkToUserAccount(Account account) {
		if(account.getUserAccountId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * Verify that AccountType id is valid.
	 * @param AccountType AccountType
	 * @return boolean
	 */
	private boolean hasLinkToAccountType(Account account) {
		if(account.getAccountTypeId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}