/*
 * Created on 6 Sep 2016 ( Time 17:16:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.model;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 45 )
    private String accountName;


    private Double originalBalance;


    private Double currentBalance;


    private Date dateOpened;


    private Date dateClosed;


    private Date dateCreated;


    private Date dateModified;

    @NotNull
    private Integer accountTypeId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAccountName( String accountName ) {
        this.accountName = accountName;
    }
    public String getAccountName() {
        return this.accountName;
    }

    public void setOriginalBalance( Double originalBalance ) {
        this.originalBalance = originalBalance;
    }
    public Double getOriginalBalance() {
        return this.originalBalance;
    }

    public void setCurrentBalance( Double currentBalance ) {
        this.currentBalance = currentBalance;
    }
    public Double getCurrentBalance() {
        return this.currentBalance;
    }

    public void setDateOpened( Date dateOpened ) {
        this.dateOpened = dateOpened;
    }
    public Date getDateOpened() {
        return this.dateOpened;
    }

    public void setDateClosed( Date dateClosed ) {
        this.dateClosed = dateClosed;
    }
    public Date getDateClosed() {
        return this.dateClosed;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }

    public void setAccountTypeId( Integer accountTypeId ) {
        this.accountTypeId = accountTypeId;
    }
    public Integer getAccountTypeId() {
        return this.accountTypeId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        return this.accountName;
    } 


}
