/*
 * Created on 24 Nov 2016 ( Time 14:57:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.model;

import com.kumasi.debtmonkey.business.service.PaymentScheduleCalculator;
import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;
import org.jboss.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;

public class PaymentSchedule implements Serializable {
    private Logger logger = Logger.getLogger(PaymentSchedule.class);
    private static final long serialVersionUID = 1L;

    @Autowired
    private PaymentScheduleCalculator calculator;
    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Date nextPaymentDue;


    private Date dateLastPayment;
    
    private Double balanceDue;

    @NotNull
    private Integer accountId;

    private String accountName;

    private Byte autoPayment;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }

    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    public Date getDateLastPayment() {        
        return dateLastPayment;
    }
    public void setDateLastPayment(Date calcDate) {        
        dateLastPayment = calcDate;
    }
    
    public void setNextPaymentDue( Date nextPaymentDue ) {
        this.nextPaymentDue = nextPaymentDue;
    }
    public Date getNextPaymentDue() {
        return this.nextPaymentDue;
    }

    public void setBalanceDue( Double balanceDue ) {
        this.balanceDue = balanceDue;
    }
    public Double getBalanceDue() {
        return this.balanceDue;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAutoPayment( Byte autoPayment ) {
        this.autoPayment = autoPayment;
    }
    public Byte getAutoPayment() {
        return this.autoPayment;
    }

    /**
     * @return the accountName
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * @param accountName the accountName to set
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nextPaymentDue);
        sb.append("|");
        sb.append(balanceDue);
        sb.append("|");
        sb.append(accountId);
        sb.append("|");
        sb.append(autoPayment);
        return sb.toString(); 
    }     

    
}
