/*
 * Created on 6 Sep 2016 ( Time 17:16:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.test.persistence;


import com.kumasi.debtmonkey.model.jpa.AccountEntity;
import com.kumasi.debtmonkey.mock.AccountEntityMock;
import com.kumasi.debtmonkey.persistence.PersistenceServiceProvider;
import com.kumasi.debtmonkey.persistence.services.AccountPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Account persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AccountPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		AccountPersistence service = PersistenceServiceProvider.getService(AccountPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Account persistence : delete + load ..." );
		
		AccountPersistence service = PersistenceServiceProvider.getService(AccountPersistence.class);
		
		AccountEntityMock mock = new AccountEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(AccountPersistence service, AccountEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		AccountEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . AccountType
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
