
/*
 * Created on 6 Sep 2016 ( Time 17:16:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.debtmonkey.model.jpa.AccountTypeEntity;
import com.kumasi.debtmonkey.mock.tool.MockValues;

public class AccountTypeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AccountTypeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AccountTypeEntity createInstance( Integer id ) {
		AccountTypeEntity entity = new AccountTypeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setAccountCode( mockValues.nextString(6) ) ; // java.lang.String 
		entity.setAccountName( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAccount( TODO ) ; // List<Account> 
		// setListOfAccountAddress( TODO ) ; // List<AccountAddress> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AccountTypeEntity> createList(int count) {
		List<AccountTypeEntity> list = new LinkedList<AccountTypeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
