
/*
 * Created on 6 Sep 2016 ( Time 17:16:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.debtmonkey.model.jpa.AccountEntity;
import com.kumasi.debtmonkey.mock.tool.MockValues;

public class AccountEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AccountEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AccountEntity createInstance( Integer id ) {
		AccountEntity entity = new AccountEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setAccountName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setOriginalBalance( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setCurrentBalance( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setDateOpened( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateClosed( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateCreated( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfAccountAddress( TODO ) ; // List<AccountAddress> 
		// setListOfPaymentSchedule( TODO ) ; // List<PaymentSchedule> 
		// setAccountType( TODO ) ; // AccountType 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AccountEntity> createList(int count) {
		List<AccountEntity> list = new LinkedList<AccountEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
