/*
 * Created on 11 Feb 2017 ( Time 18:00:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.debtmonkey.model.Account;
import com.kumasi.debtmonkey.model.jpa.AccountEntity;
import com.kumasi.debtmonkey.model.jpa.UserAccountEntity;
import com.kumasi.debtmonkey.model.jpa.AccountTypeEntity;
import com.kumasi.debtmonkey.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class AccountServiceMapperTest {

	private AccountServiceMapper accountServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		accountServiceMapper = new AccountServiceMapper();
		accountServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'AccountEntity' to 'Account'
	 * @param accountEntity
	 */
	@Test
	public void testMapAccountEntityToAccount() {
		// Given
		AccountEntity accountEntity = new AccountEntity();
		accountEntity.setAccountName(mockValues.nextString(45));
		accountEntity.setOriginalBalance(mockValues.nextDouble());
		accountEntity.setCurrentBalance(mockValues.nextDouble());
		accountEntity.setDateLastPayment(mockValues.nextDate());
		accountEntity.setDateOpened(mockValues.nextDate());
		accountEntity.setDateClosed(mockValues.nextDate());
		accountEntity.setDateCreated(mockValues.nextDate());
		accountEntity.setDateModified(mockValues.nextDate());
		accountEntity.setAutoPayment(mockValues.nextByte());
		accountEntity.setUserAccount(new UserAccountEntity());
		accountEntity.getUserAccount().setId(mockValues.nextInteger());
		accountEntity.setAccountType(new AccountTypeEntity());
		accountEntity.getAccountType().setId(mockValues.nextInteger());
		
		// When
		Account account = accountServiceMapper.mapAccountEntityToAccount(accountEntity);
		
		// Then
		assertEquals(accountEntity.getAccountName(), account.getAccountName());
		assertEquals(accountEntity.getOriginalBalance(), account.getOriginalBalance());
		assertEquals(accountEntity.getCurrentBalance(), account.getCurrentBalance());
		assertEquals(accountEntity.getDateLastPayment(), account.getDateLastPayment());
		assertEquals(accountEntity.getDateOpened(), account.getDateOpened());
		assertEquals(accountEntity.getDateClosed(), account.getDateClosed());
		assertEquals(accountEntity.getDateCreated(), account.getDateCreated());
		assertEquals(accountEntity.getDateModified(), account.getDateModified());
		assertEquals(accountEntity.getAutoPayment(), account.getAutoPayment());
		assertEquals(accountEntity.getUserAccount().getId(), account.getUserAccountId());
		assertEquals(accountEntity.getAccountType().getId(), account.getAccountTypeId());
	}
	
	/**
	 * Test : Mapping from 'Account' to 'AccountEntity'
	 */
	@Test
	public void testMapAccountToAccountEntity() {
		// Given
		Account account = new Account();
		account.setAccountName(mockValues.nextString(45));
		account.setOriginalBalance(mockValues.nextDouble());
		account.setCurrentBalance(mockValues.nextDouble());
		account.setDateLastPayment(mockValues.nextDate());
		account.setDateOpened(mockValues.nextDate());
		account.setDateClosed(mockValues.nextDate());
		account.setDateCreated(mockValues.nextDate());
		account.setDateModified(mockValues.nextDate());
		account.setAutoPayment(mockValues.nextByte());
		account.setUserAccountId(mockValues.nextInteger());
		account.setAccountTypeId(mockValues.nextInteger());

		AccountEntity accountEntity = new AccountEntity();
		
		// When
		accountServiceMapper.mapAccountToAccountEntity(account, accountEntity);
		
		// Then
		assertEquals(account.getAccountName(), accountEntity.getAccountName());
		assertEquals(account.getOriginalBalance(), accountEntity.getOriginalBalance());
		assertEquals(account.getCurrentBalance(), accountEntity.getCurrentBalance());
		assertEquals(account.getDateLastPayment(), accountEntity.getDateLastPayment());
		assertEquals(account.getDateOpened(), accountEntity.getDateOpened());
		assertEquals(account.getDateClosed(), accountEntity.getDateClosed());
		assertEquals(account.getDateCreated(), accountEntity.getDateCreated());
		assertEquals(account.getDateModified(), accountEntity.getDateModified());
		assertEquals(account.getAutoPayment(), accountEntity.getAutoPayment());
		assertEquals(account.getUserAccountId(), accountEntity.getUserAccount().getId());
		assertEquals(account.getAccountTypeId(), accountEntity.getAccountType().getId());
	}

}