/*
 * Created on 11 Feb 2017 ( Time 18:00:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.debtmonkey.model.PaymentHistory;
import com.kumasi.debtmonkey.model.jpa.PaymentHistoryEntity;
import com.kumasi.debtmonkey.model.jpa.AccountEntity;
import com.kumasi.debtmonkey.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PaymentHistoryServiceMapperTest {

	private PaymentHistoryServiceMapper paymentHistoryServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		paymentHistoryServiceMapper = new PaymentHistoryServiceMapper();
		paymentHistoryServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PaymentHistoryEntity' to 'PaymentHistory'
	 * @param paymentHistoryEntity
	 */
	@Test
	public void testMapPaymentHistoryEntityToPaymentHistory() {
		// Given
		PaymentHistoryEntity paymentHistoryEntity = new PaymentHistoryEntity();
		paymentHistoryEntity.setAmountPaid(mockValues.nextDouble());
		paymentHistoryEntity.setDatePaid(mockValues.nextDate());
		paymentHistoryEntity.setDateModified(mockValues.nextDate());
		paymentHistoryEntity.setDateCreated(mockValues.nextDate());
		paymentHistoryEntity.setAccount(new AccountEntity());
		paymentHistoryEntity.getAccount().setId(mockValues.nextInteger());
		
		// When
		PaymentHistory paymentHistory = paymentHistoryServiceMapper.mapPaymentHistoryEntityToPaymentHistory(paymentHistoryEntity);
		
		// Then
		assertEquals(paymentHistoryEntity.getAmountPaid(), paymentHistory.getAmountPaid());
		assertEquals(paymentHistoryEntity.getDatePaid(), paymentHistory.getDatePaid());
		assertEquals(paymentHistoryEntity.getDateModified(), paymentHistory.getDateModified());
		assertEquals(paymentHistoryEntity.getDateCreated(), paymentHistory.getDateCreated());
		assertEquals(paymentHistoryEntity.getAccount().getId(), paymentHistory.getAccountId());
	}
	
	/**
	 * Test : Mapping from 'PaymentHistory' to 'PaymentHistoryEntity'
	 */
	@Test
	public void testMapPaymentHistoryToPaymentHistoryEntity() {
		// Given
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setAmountPaid(mockValues.nextDouble());
		paymentHistory.setDatePaid(mockValues.nextDate());
		paymentHistory.setDateModified(mockValues.nextDate());
		paymentHistory.setDateCreated(mockValues.nextDate());
		paymentHistory.setAccountId(mockValues.nextInteger());

		PaymentHistoryEntity paymentHistoryEntity = new PaymentHistoryEntity();
		
		// When
		paymentHistoryServiceMapper.mapPaymentHistoryToPaymentHistoryEntity(paymentHistory, paymentHistoryEntity);
		
		// Then
		assertEquals(paymentHistory.getAmountPaid(), paymentHistoryEntity.getAmountPaid());
		assertEquals(paymentHistory.getDatePaid(), paymentHistoryEntity.getDatePaid());
		assertEquals(paymentHistory.getDateModified(), paymentHistoryEntity.getDateModified());
		assertEquals(paymentHistory.getDateCreated(), paymentHistoryEntity.getDateCreated());
		assertEquals(paymentHistory.getAccountId(), paymentHistoryEntity.getAccount().getId());
	}

}