/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.debtmonkey.domain.jpa.UserRoleEntity;

/**
 * Basic persistence operations for entity "UserRole"
 * 
 * This Bean has a composite Primary Key : UserRoleEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface UserRolePersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userRole
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(UserRoleEntity userRole) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userAccountId
	 * @param roleRoleId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer userAccountId, Integer roleRoleId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userRole
	 */
	public void insert(UserRoleEntity userRole) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param userAccountId
	 * @param roleRoleId
	 * @return the entity loaded (or null if not found)
	 */
	public UserRoleEntity load(Integer userAccountId, Integer roleRoleId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<UserRoleEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<UserRoleEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<UserRoleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userRole
	 * @return
	 */
	public UserRoleEntity save(UserRoleEntity userRole) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<UserRoleEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
