/*
 * Created on 6 Sep 2016 ( Time 17:16:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.debtmonkey.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.debtmonkey.model.jpa.AddressTypeEntity;
import com.kumasi.debtmonkey.persistence.commons.jpa.GenericJpaService;
import com.kumasi.debtmonkey.persistence.commons.jpa.JpaOperation;
import com.kumasi.debtmonkey.persistence.services.AddressTypePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "AddressType" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AddressTypePersistenceJPA extends GenericJpaService<AddressTypeEntity, Integer> implements AddressTypePersistence {

	/**
	 * Constructor
	 */
	public AddressTypePersistenceJPA() {
		super(AddressTypeEntity.class);
	}

	@Override
	public AddressTypeEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(AddressTypeEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("AddressTypeEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
