
/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.debtmonkey.domain.jpa.AddressTypeEntity;
import net.kumasi.debtmonkey.mock.tool.MockValues;

public class AddressTypeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AddressTypeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AddressTypeEntity createInstance( Integer id ) {
		AddressTypeEntity entity = new AddressTypeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setAddressCode( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAccountAddress( TODO ) ; // List<AccountAddress> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AddressTypeEntity> createList(int count) {
		List<AddressTypeEntity> list = new LinkedList<AddressTypeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
