
/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.debtmonkey.domain.jpa.PaymentHistoryEntity;
import net.kumasi.debtmonkey.mock.tool.MockValues;

public class PaymentHistoryEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PaymentHistoryEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PaymentHistoryEntity createInstance( Integer idpaymentHistory ) {
		PaymentHistoryEntity entity = new PaymentHistoryEntity();
		// Init Primary Key fields
		entity.setIdpaymentHistory( idpaymentHistory) ;
		// Init Data fields
		entity.setAmountPaid( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setDatePaid( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateCreated( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setAccount( TODO ) ; // Account 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PaymentHistoryEntity> createList(int count) {
		List<PaymentHistoryEntity> list = new LinkedList<PaymentHistoryEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
