
/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.debtmonkey.domain.jpa.UserAccountEntity;
import net.kumasi.debtmonkey.mock.tool.MockValues;

public class UserAccountEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UserAccountEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UserAccountEntity createInstance( Integer id ) {
		UserAccountEntity entity = new UserAccountEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setUserName( mockValues.nextString(15) ) ; // java.lang.String 
		entity.setEmailAddress( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setFirstName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfRole( TODO ) ; // List<Role> 
		// setListOfAccount( TODO ) ; // List<Account> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UserAccountEntity> createList(int count) {
		List<UserAccountEntity> list = new LinkedList<UserAccountEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
