/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package net.kumasi.debtmonkey.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Account_Address"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Account_Address", catalog="homeAccount" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccountAddressEntity.countAll", query="SELECT COUNT(x) FROM AccountAddressEntity x" )
} )
public class AccountAddressEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="address_line_1", length=45)
    private String     addressLine1 ;

    @Column(name="address_line_2", length=45)
    private String     addressLine2 ;

    @Column(name="city", length=45)
    private String     city         ;

    @Column(name="state", length=45)
    private String     state        ;

    @Column(name="zipcode", length=5)
    private String     zipcode      ;

	// "addressTypeId" (column "Address_Type_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="Address_Type_id", referencedColumnName="id")
    private AddressTypeEntity addressType ;

    @OneToMany(mappedBy="accountAddress", targetEntity=AccountEntity.class)
    private List<AccountEntity> listOfAccount;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccountAddressEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : address_line_1 ( VARCHAR ) 
    public void setAddressLine1( String addressLine1 ) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }

    //--- DATABASE MAPPING : address_line_2 ( VARCHAR ) 
    public void setAddressLine2( String addressLine2 ) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }

    //--- DATABASE MAPPING : city ( VARCHAR ) 
    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    //--- DATABASE MAPPING : state ( VARCHAR ) 
    public void setState( String state ) {
        this.state = state;
    }
    public String getState() {
        return this.state;
    }

    //--- DATABASE MAPPING : zipcode ( VARCHAR ) 
    public void setZipcode( String zipcode ) {
        this.zipcode = zipcode;
    }
    public String getZipcode() {
        return this.zipcode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAddressType( AddressTypeEntity addressType ) {
        this.addressType = addressType;
    }
    public AddressTypeEntity getAddressType() {
        return this.addressType;
    }

    public void setListOfAccount( List<AccountEntity> listOfAccount ) {
        this.listOfAccount = listOfAccount;
    }
    public List<AccountEntity> getListOfAccount() {
        return this.listOfAccount;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(addressLine1);
        sb.append("|");
        sb.append(addressLine2);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(zipcode);
        return sb.toString(); 
    } 

}
