/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package net.kumasi.debtmonkey.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Role"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Role", catalog="homeAccount" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RoleEntity.countAll", query="SELECT COUNT(x) FROM RoleEntity x" )
} )
public class RoleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="role_id", nullable=false)
    private Integer    roleId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="role_name", length=255)
    private String     roleName     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToMany(targetEntity=UserAccountEntity.class)
    @JoinTable(name="User_Role", 
      joinColumns=@JoinColumn(name="Role_role_id", referencedColumnName="role_id"),
      inverseJoinColumns=@JoinColumn(name="User_Account_id", referencedColumnName="id")
     ) 

    private List<UserAccountEntity> listOfUserAccount;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RoleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : role_name ( VARCHAR ) 
    public void setRoleName( String roleName ) {
        this.roleName = roleName;
    }
    public String getRoleName() {
        return this.roleName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUserAccount( List<UserAccountEntity> listOfUserAccount ) {
        this.listOfUserAccount = listOfUserAccount;
    }
    public List<UserAccountEntity> getListOfUserAccount() {
        return this.listOfUserAccount;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(roleId);
        sb.append("]:"); 
        sb.append(roleName);
        return sb.toString(); 
    } 

}
