/*
 * Created on 17 Feb 2017 ( Time 16:36:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.domain.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "UserRoleEntity" ( stored in table "User_Role" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class UserRoleEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="User_Account_id", nullable=false)
    private Integer    userAccountId ;
    
    @Column(name="Role_role_id", nullable=false)
    private Integer    roleRoleId   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public UserRoleEntityKey() {
        super();
    }

    public UserRoleEntityKey( Integer userAccountId, Integer roleRoleId ) {
        super();
        this.userAccountId = userAccountId ;
        this.roleRoleId = roleRoleId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUserAccountId( Integer value ) {
        this.userAccountId = value;
    }
    public Integer getUserAccountId() {
        return this.userAccountId;
    }

    public void setRoleRoleId( Integer value ) {
        this.roleRoleId = value;
    }
    public Integer getRoleRoleId() {
        return this.roleRoleId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		UserRoleEntityKey other = (UserRoleEntityKey) obj; 
		//--- Attribute userAccountId
		if ( userAccountId == null ) { 
			if ( other.userAccountId != null ) 
				return false ; 
		} else if ( ! userAccountId.equals(other.userAccountId) ) 
			return false ; 
		//--- Attribute roleRoleId
		if ( roleRoleId == null ) { 
			if ( other.roleRoleId != null ) 
				return false ; 
		} else if ( ! roleRoleId.equals(other.roleRoleId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute userAccountId
		result = prime * result + ((userAccountId == null) ? 0 : userAccountId.hashCode() ) ; 
		//--- Attribute roleRoleId
		result = prime * result + ((roleRoleId == null) ? 0 : roleRoleId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(userAccountId); 
		sb.append("|"); 
		sb.append(roleRoleId); 
        return sb.toString();
    }
}
