/*
 * Created on 17 Feb 2017 ( Time 16:36:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkey.domain.AddressType;
import net.kumasi.debtmonkey.domain.jpa.AddressTypeEntity;
import net.kumasi.debtmonkey.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class AddressTypeServiceMapperTest {

	private AddressTypeServiceMapper addressTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		addressTypeServiceMapper = new AddressTypeServiceMapper();
		addressTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'AddressTypeEntity' to 'AddressType'
	 * @param addressTypeEntity
	 */
	@Test
	public void testMapAddressTypeEntityToAddressType() {
		// Given
		AddressTypeEntity addressTypeEntity = new AddressTypeEntity();
		addressTypeEntity.setAddressCode(mockValues.nextString(45));
		
		// When
		AddressType addressType = addressTypeServiceMapper.mapAddressTypeEntityToAddressType(addressTypeEntity);
		
		// Then
		assertEquals(addressTypeEntity.getAddressCode(), addressType.getAddressCode());
	}
	
	/**
	 * Test : Mapping from 'AddressType' to 'AddressTypeEntity'
	 */
	@Test
	public void testMapAddressTypeToAddressTypeEntity() {
		// Given
		AddressType addressType = new AddressType();
		addressType.setAddressCode(mockValues.nextString(45));

		AddressTypeEntity addressTypeEntity = new AddressTypeEntity();
		
		// When
		addressTypeServiceMapper.mapAddressTypeToAddressTypeEntity(addressType, addressTypeEntity);
		
		// Then
		assertEquals(addressType.getAddressCode(), addressTypeEntity.getAddressCode());
	}

}