/*
 * Created on 17 Feb 2017 ( Time 16:36:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkey.domain.Role;
import net.kumasi.debtmonkey.domain.jpa.RoleEntity;
import net.kumasi.debtmonkey.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class RoleServiceMapperTest {

	private RoleServiceMapper roleServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		roleServiceMapper = new RoleServiceMapper();
		roleServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'RoleEntity' to 'Role'
	 * @param roleEntity
	 */
	@Test
	public void testMapRoleEntityToRole() {
		// Given
		RoleEntity roleEntity = new RoleEntity();
		roleEntity.setRoleName(mockValues.nextString(255));
		
		// When
		Role role = roleServiceMapper.mapRoleEntityToRole(roleEntity);
		
		// Then
		assertEquals(roleEntity.getRoleName(), role.getRoleName());
	}
	
	/**
	 * Test : Mapping from 'Role' to 'RoleEntity'
	 */
	@Test
	public void testMapRoleToRoleEntity() {
		// Given
		Role role = new Role();
		role.setRoleName(mockValues.nextString(255));

		RoleEntity roleEntity = new RoleEntity();
		
		// When
		roleServiceMapper.mapRoleToRoleEntity(role, roleEntity);
		
		// Then
		assertEquals(role.getRoleName(), roleEntity.getRoleName());
	}

}