/*
 * Created on 17 Feb 2017 ( Time 16:36:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.debtmonkey.domain.UserRole;
import net.kumasi.debtmonkey.domain.jpa.UserRoleEntity;
import net.kumasi.debtmonkey.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class UserRoleServiceMapperTest {

	private UserRoleServiceMapper userRoleServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		userRoleServiceMapper = new UserRoleServiceMapper();
		userRoleServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'UserRoleEntity' to 'UserRole'
	 * @param userRoleEntity
	 */
	@Test
	public void testMapUserRoleEntityToUserRole() {
		// Given
		UserRoleEntity userRoleEntity = new UserRoleEntity();
		
		// When
		UserRole userRole = userRoleServiceMapper.mapUserRoleEntityToUserRole(userRoleEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'UserRole' to 'UserRoleEntity'
	 */
	@Test
	public void testMapUserRoleToUserRoleEntity() {
		// Given
		UserRole userRole = new UserRole();

		UserRoleEntity userRoleEntity = new UserRoleEntity();
		
		// When
		userRoleServiceMapper.mapUserRoleToUserRoleEntity(userRole, userRoleEntity);
		
		// Then
	}

}