/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.domain;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 45 )
    private String accountName;


    private Double originalBalance;


    private Double currentBalance;


    private Date dateLastPayment;


    private Date dateOpened;


    private Date dateClosed;


    private Date dateCreated;


    private Date dateModified;

    @NotNull
    private Integer accountTypeId;


    private Byte autoPayment;


    private Integer userAccountId;


    private Integer accountAddressId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAccountName( String accountName ) {
        this.accountName = accountName;
    }
    public String getAccountName() {
        return this.accountName;
    }

    public void setOriginalBalance( Double originalBalance ) {
        this.originalBalance = originalBalance;
    }
    public Double getOriginalBalance() {
        return this.originalBalance;
    }

    public void setCurrentBalance( Double currentBalance ) {
        this.currentBalance = currentBalance;
    }
    public Double getCurrentBalance() {
        return this.currentBalance;
    }

    public void setDateLastPayment( Date dateLastPayment ) {
        this.dateLastPayment = dateLastPayment;
    }
    public Date getDateLastPayment() {
        return this.dateLastPayment;
    }

    public void setDateOpened( Date dateOpened ) {
        this.dateOpened = dateOpened;
    }
    public Date getDateOpened() {
        return this.dateOpened;
    }

    public void setDateClosed( Date dateClosed ) {
        this.dateClosed = dateClosed;
    }
    public Date getDateClosed() {
        return this.dateClosed;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }

    public void setAccountTypeId( Integer accountTypeId ) {
        this.accountTypeId = accountTypeId;
    }
    public Integer getAccountTypeId() {
        return this.accountTypeId;
    }

    public void setAutoPayment( Byte autoPayment ) {
        this.autoPayment = autoPayment;
    }
    public Byte getAutoPayment() {
        return this.autoPayment;
    }

    public void setUserAccountId( Integer userAccountId ) {
        this.userAccountId = userAccountId;
    }
    public Integer getUserAccountId() {
        return this.userAccountId;
    }

    public void setAccountAddressId( Integer accountAddressId ) {
        this.accountAddressId = accountAddressId;
    }
    public Integer getAccountAddressId() {
        return this.accountAddressId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(accountName);
        sb.append("|");
        sb.append(originalBalance);
        sb.append("|");
        sb.append(currentBalance);
        sb.append("|");
        sb.append(dateLastPayment);
        sb.append("|");
        sb.append(dateOpened);
        sb.append("|");
        sb.append(dateClosed);
        sb.append("|");
        sb.append(dateCreated);
        sb.append("|");
        sb.append(dateModified);
        sb.append("|");
        sb.append(accountTypeId);
        sb.append("|");
        sb.append(autoPayment);
        sb.append("|");
        sb.append(userAccountId);
        sb.append("|");
        sb.append(accountAddressId);
        return sb.toString(); 
    } 


}
