/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.domain;

import java.io.Serializable;

import javax.validation.constraints.*;


public class AccountAddress implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 45 )
    private String addressLine1;

    @Size( max = 45 )
    private String addressLine2;

    @Size( max = 45 )
    private String city;

    @Size( max = 45 )
    private String state;

    @Size( max = 5 )
    private String zipcode;

    @NotNull
    private AddressType addressType;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAddressLine1( String addressLine1 ) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine2( String addressLine2 ) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setState( String state ) {
        this.state = state;
    }
    public String getState() {
        return this.state;
    }

    public void setZipcode( String zipcode ) {
        this.zipcode = zipcode;
    }
    public String getZipcode() {
        return this.zipcode;
    }

    public void setAddressType( AddressType addressTypeId ) {
        this.addressType = addressType;
    }
    
    public AddressType getAddressType() {
		return addressType;
	}

	public Integer getAddressTypeId() {
		if(addressType == null) {
			return 0;
		}else{
			return this.addressType.getId();	
		}
        
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(addressLine1);
        sb.append("|");
        sb.append(addressLine2);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(zipcode);
        sb.append("|");
        sb.append(addressType);
        return sb.toString(); 
    } 


}
