/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.domain;

import java.io.Serializable;

import javax.validation.constraints.*;


public class UserRole implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer userAccountId;
    @NotNull
    private Integer roleRoleId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserAccountId( Integer userAccountId ) {
        this.userAccountId = userAccountId ;
    }

    public Integer getUserAccountId() {
        return this.userAccountId;
    }

    public void setRoleRoleId( Integer roleRoleId ) {
        this.roleRoleId = roleRoleId ;
    }

    public Integer getRoleRoleId() {
        return this.roleRoleId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userAccountId);
        sb.append("|");
        sb.append(roleRoleId);
        return sb.toString(); 
    } 


}
