/*
 * Created on 17 Feb 2017 ( Time 16:36:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.debtmonkey.web.listitem;

import net.kumasi.debtmonkey.domain.AccountAddress;
import net.kumasi.debtmonkey.web.common.ListItem;

public class AccountAddressListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public AccountAddressListItem(AccountAddress accountAddress) {
		super();

		this.value = ""
			 + accountAddress.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = accountAddress.getAddressLine1()+" "+accountAddress.getCity()+" "+accountAddress.getState()+" "+accountAddress.getZipcode();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
