/*
 * Created on 11 Feb 2017 ( Time 18:00:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.debtmonkey.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.debtmonkey.model.jpa.PaymentScheduleEntity;
import com.kumasi.debtmonkey.persistence.commons.fake.GenericFakeService;
import com.kumasi.debtmonkey.persistence.services.PaymentSchedulePersistence;

/**
 * Fake persistence service implementation ( entity "PaymentSchedule" )
 *
 * @author Telosys Tools Generator
 */
public class PaymentSchedulePersistenceFAKE extends GenericFakeService<PaymentScheduleEntity> implements PaymentSchedulePersistence {

	public PaymentSchedulePersistenceFAKE () {
		super(PaymentScheduleEntity.class);
	}
	
	protected PaymentScheduleEntity buildEntity(int index) {
		PaymentScheduleEntity entity = new PaymentScheduleEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setNextPaymentDue( nextDate() ) ;
		entity.setBalanceDue( nextDouble() ) ;
		entity.setAutoPayment( nextByte() ) ;
		return entity ;
	}
	
	
	public boolean delete(PaymentScheduleEntity entity) {
		log("delete ( PaymentScheduleEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PaymentScheduleEntity entity) {
		log("insert ( PaymentScheduleEntity : " + entity + ")" ) ;
	}

	public PaymentScheduleEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PaymentScheduleEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PaymentScheduleEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PaymentScheduleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PaymentScheduleEntity save(PaymentScheduleEntity entity) {
		log("insert ( PaymentScheduleEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PaymentScheduleEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
